### ISSUE TITLE
fails on RHEL 7 perl 5.16.3

### ISSUE THREAD

**Issue by peterdragon** [alnewkirk/Type-Tiny-Signatures#2]
t/main-strict.t ... Undefined type name main::Str at t/main-strict.t line 6.

same error as
http://www.cpantesters.org/cpan/report/c49e41e4-6280-11e7-92fb-c34b4beb1795

**Comment by alnewkirk** [comment]
Thanks for the report. Sorry for the late reply! This has been fixed, which you can verify by checking https://travis-ci.org/alnewkirk/Type-Tiny-Signatures/jobs/467513644
